/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Clément' at '17/02/16 09:44' with Gradle 2.6
 *
 * @author Clément, @date 17/02/16 09:44
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
